[package]
name = "ecat-config-remote"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Remote configuration source for e-cat"

[dependencies]
ecat-config = { path = "../ecat-config" }
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
