[package]
name = "ecat"
version.workspace = true
edition.workspace = true

[dependencies]
ecat-transport = { path = "../ecat-transport" }
ecat-transport-http = { path = "../ecat-transport-http" }
ecat-transport-grpc = { path = "../ecat-transport-grpc" }
ecat-logging = { path = "../ecat-logging" }
ecat-errors = { path = "../ecat-errors" }
tokio.workspace = true
tracing.workspace = true
async-trait.workspace = true
