[package]
name = "ecat-transport-ws"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WebSocket transport implementation for e-cat"

[dependencies]
ecat-transport = { path = "../ecat-transport" }
tokio.workspace = true
async-trait.workspace = true
axum = { workspace = true, features = ["ws"] }
tower.workspace = true
futures-util = "0.3"
