[package]
name = "ecat-errors"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Unified error types for e-cat services"

[dependencies]
ecat-protos = { path = "../ecat-protos" }
prost.workspace = true
thiserror.workspace = true
serde.workspace = true
http.workspace = true
tonic.workspace = true
