[package]
name = "ecat-mq-mqtt"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "MQTT message queue backend for e-cat"

[dependencies]
ecat-mq = { path = "../ecat-mq" }
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
rumqttc = "0.25"
